baseurl = "https://okpanda.netlify.app/"
title = "熊貓電腦"
author = "熊貓"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = false

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "熊貓電腦"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "所有活動"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "關於熊貓電腦"
    url = "/post/about"
    weight = 2
[[menu.primary]]
    name = "價目表"
    url = "/post/price"
    weight = 3
[[menu.primary]]
    name = "聯絡方式"
    url = "/post/contact"
    weight = 4
[[menu.primary]]
    name = "售後服務"
    url = "/post/service"
    weight = 5